### ISSUE TITLE
Practica Hilos

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/practica-de-hilos-JazminloRI#2]
[Reporte de Práctica -Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-JazminloRI/files/6499608/Reporte.de.Practica.-Hilos.pdf)

**Comment by Eva155** [comment]
CALIFICACIÓN: 20 PUNTOS
CALIFICÓ: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
